services:
  motorcycle_weather:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account-key.json
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
    ports:
      - "8000:8000"
    volumes:
      - ./server:/Motorcycle_Weather/server
      - ./service-account-key.json:/app/service-account-key.json:ro
    container_name: motorcycle_weather_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
