services:
  motorcycle-weather:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    working_dir: /motorcycle-weather
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./:/motorcycle-weather
    container_name: motorcycle-weather-app

  db:
    image: postgres:16
    container_name: motorcycle-weather-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: motorcycle-weather-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
