services:
  motorcycle_weather:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      ENVIRONMENT: production
      PORT: 8000
    ports:
      - "8000:8000"
    container_name: motorcycle_weather_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # No volume mounts for production - code is baked into container
    # No --reload flag - production mode only