[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
ENVIRONMENT = "production"
PORT = "8000"

[environments.staging]
[environments.staging.variables]
ENVIRONMENT = "staging"
PORT = "8000"